##
## Copyright (c) 2019-2020
##
## @author: Daniel Bankmann
## @company: Technische Universität Berlin
##
## This file is part of the python package pymloc
## (see https://gitlab.tubit.tu-berlin.de/bankmann91/python-mloc )
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##
---

version: 1
disable_existing_loggers: True
formatters:
    console:
        class: colorlog.ColoredFormatter
        format: "%(log_color)s%(level_indent)s%(message)s"
    console_debug:
        class: colorlog.ColoredFormatter
        format: "%(log_color)s%(level_indent)s%(message)s (%(filename)s:%(lineno)s)"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: console
        stream: ext://sys.stdout
    console_debug:
        class: logging.StreamHandler
        level: DEBUG
        formatter: console_debug
        stream: ext://sys.stdout

root:
    level: INFO
    handlers: [console]
