---

version: 1
disable_existing_loggers: True
formatters:
    console:
        class: colorlog.ColoredFormatter
        format: "%(log_color)s%(level_indent)s%(message)s (%(filename)s:%(lineno)s)"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: console
        stream: ext://sys.stdout


root:
    level: DEBUG
    handlers: [console]
